version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETOS: linux
        TARGETARCH: amd64
    restart: unless-stopped
    volumes:
      - "./config:/app/config"
      - "./app:/app/app"
      - "./routes:/app/routes"
      - "./themes:/app/themes"
      - "./lang:/app/lang"
      - "./extensions:/app/extensions"
      - "./storage/logs:/app/storage/logs"
      - "./storage/public:/app/storage/app/public"
      - "./storage/framework/cache:/app/storage/framework/cache"
      - "./database:/app/database"
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - database
      - cache

  database:
    image: mariadb:lts
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: paymenter
      MYSQL_USER: paymenter
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: laravel_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mariadb_data:
