x-common:
  database:
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Paymenter functionality.
    &db-environment
    MYSQL_PASSWORD: &db-password "${DB_PASSWORD:-CHANGE_ME}"
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-CHANGE_ME_TOO}"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:lts
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_EXTERNAL_PORT:-3309}:3306"
    volumes:
      - "mariadb_data:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "${DB_DATABASE:-paymenter}"
      MYSQL_USER: "${DB_USERNAME:-paymenter}"
  cache:
    image: redis:alpine
    restart: always
  paymenter:
    build: .
    restart: always
    ports:
      - "${APP_PORT:-80}:80"
    links:
      - database
      - cache
    volumes:
      - "./config:/app/config"
      - "./app:/app/app"
      - "./routes:/app/routes"
      - "./themes:/app/themes"
      - "./lang:/app/lang"
      - "./extensions:/app/extensions"
      - "./.env/:/app/.env"
      - "./storage/logs:/app/storage/logs"
      - "./storage/public:/app/storage/app/public"
      - "./storage/framework/cache:/app/storage/framework/cache"
      - "./database:/app/database"
    environment:
      DB_PASSWORD: *db-password
      APP_ENV: "${APP_ENV:-local}"
      APP_DEBUG: "${APP_DEBUG:-true}"
      CACHE_STORE: "${CACHE_STORE:-redis}"
      REDIS_HOST: "${REDIS_HOST:-cache}"
      DB_CONNECTION: "${DB_CONNECTION:-mariadb}"
      DB_HOST: "${DB_HOST:-database}"
      DB_PORT: "${DB_PORT:-3306}"
networks:
  default:
    ipam:
      config:
        - subnet: 172.23.0.0/16
volumes:
  mariadb_data:
