[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=/var/log/supervisord/supervisord.log
logfile_maxbytes=50MB
logfile_backups=2
loglevel=info              ; "error" hides useful runtime info
pidfile=/var/run/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200
user=root
childlogdir=/var/log/supervisord/

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

; -------------------------------
; PHP-FPM
; -------------------------------
[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
priority=5
stdout_logfile=/var/log/php-fpm.log
redirect_stderr=true

; -------------------------------
; Laravel Queue Worker
; -------------------------------
[program:queue-worker]
command=/usr/local/bin/php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600
user=nginx
autostart=true
autorestart=true
priority=20
redirect_stderr=true
stdout_logfile=/var/log/laravel-queue.log
stopasgroup=true
killasgroup=true

; -------------------------------
; Nginx
; -------------------------------
[program:nginx]
user=nginx
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/nginx-supervisor.log
redirect_stderr=true
