[www]

user = root
group = root

listen = 127.0.0.1:9000
listen.owner = root
listen.group = root
listen.mode = 0750

pm = ondemand
pm.max_children = 200
pm.process_idle_timeout = 1s
pm.max_requests = 1000

clear_env = no